name: PockCart
options:
  bundleIdPrefix: SQLI.pock-cart-courseu
targets:
  PockCart:
    type: application
    platform: iOS
    deploymentTarget: "16.2"
    sources: [PockCart]
    info:
      path: PockCart/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        ApplicationSupportsIndirectInputEvents: YES
        MainStoryboardFile: Main
    settings:
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      TARGETED_DEVICE_FAMILY: 1
      SWIFT_VERSION: 5.0
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: KX79BU5A78
      GENERATE_INFOPLIST_FILE: YES
    depencencies:
      target: [PockCartData]
  PockCartData:
    type: framework
    platform: iOS
    sources: [PockCartData]
    settings:
      GENERATE_INFOPLIST_FILE: YES
  PockCartTests:
    type: bundle.unit-test
    platform: iOS
    sources: [PockCartTests]
    settings:
      base:
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_FILE: 'Generated Supporting Files/FrameworkTestsInfo.plist'
        PRODUCT_NAME: PockCartTests
    depencencies:
      target: [PockCart]



